# -*- mode: ruby -*-
# vi: set ft=ruby :

SERVER_NAME = "sanaggarS"
SERVER_IP = "192.168.56.110"

Vagrant.configure("2") do |config|
  
  config.vm.box = "bento/ubuntu-24.04"
  
  # Dossier partagé pour les configs K8s
  config.vm.synced_folder "./confs", "/vagrant_confs", create: true

  config.vm.define SERVER_NAME do |server|
    server.vm.hostname = SERVER_NAME
    server.vm.network "private_network", ip: SERVER_IP
    
    server.vm.provider "virtualbox" do |vb|
      vb.name = SERVER_NAME
      vb.memory = "1024"
      vb.cpus = 1
    end
    
    # Script d'installation K3s + déploiement des apps
    server.vm.provision "shell", path: "scripts/setup.sh"
  end

end
